Add logging to capture swap requests, partner offers, and errors.
EdgeApp/edge-exchange-plugins pull request #111
Opened 2021-01-02 02:05 UTC by peachbits

2021-01-02 02:50 UTC, paullinator requested changes
Please check that the errors logged are appropriate for the actual error. I marked a dozen but I did not fully check the rest of the PR. It looks like it is a recurring issue.

2021-01-02 02:50 UTC, paullinator commented on src/swap/foxExchange.js
> +              `${pluginId} SwapBelowLimitError\n${JSON.stringify(
should be SwapAboveLimitError

2021-01-02 02:50 UTC, paullinator commented on src/swap/changelly.js
> +      checkReply(sendReply, request, log)
Line 193 should have a log noting that the fixed rate quote failed. As well, it should log if the estimate quote also fails

2021-01-02 02:50 UTC, paullinator commented on src/swap/coinswitch.js
> +          `${pluginId} SwapBelowLimitError\n${JSON.stringify(
SwapAboveLimitError

2021-01-02 02:50 UTC, paullinator commented on src/swap/coinswitch.js
> +          `${pluginId} SwapBelowLimitError\n${JSON.stringify(
SwapAboveLimitError

2021-01-02 02:50 UTC, paullinator commented on src/swap/faast.js
> +        `${pluginId} SwapBelowLimitError\n${JSON.stringify(
SwapPermissionError

2021-01-02 02:50 UTC, paullinator commented on src/swap/faast.js
> +          `${pluginId} SwapBelowLimitError\n${JSON.stringify(
SwapPermissionError

2021-01-02 02:50 UTC, paullinator commented on src/swap/faast.js
> +          `${pluginId} SwapBelowLimitError\n${JSON.stringify(
SwapAboveLimitError

2021-01-02 02:50 UTC, paullinator commented on src/swap/faast.js
> +            `${pluginId} SwapBelowLimitError\n${JSON.stringify(swapInfo)}\n${
SwapAboveLimitError

2021-01-02 02:50 UTC, paullinator commented on src/swap/foxExchange.js
> +              `${pluginId} SwapBelowLimitError\n${JSON.stringify(
SwapPermissionError

2021-01-02 02:50 UTC, paullinator commented on src/swap/foxExchange.js
> +              `${pluginId} SwapBelowLimitError\n${JSON.stringify(swapInfo)}\n${
SwapAboveLimitError

2021-01-12 00:17 UTC, swansontec reviewed
I agree that we should return more specific errors (above / below limits, for instance), but logging the inputs & outputs (or errors) of every single quote plugin is not a good approach - the core can simply log the swap request, and then log all the results (or errors) as they come in. We already have similar logic in the core, which tried to be a bit more balanced in its reporting, but if we want to turn up the verbosity, let's do it in the core.

2021-01-12 00:17 UTC, swansontec commented on src/swap/changelly.js
> +      log.warn(`${pluginId} swap requested ${JSON.stringify(request)}`)
Again, we are going to get a ton of redundant logs this way. The core should simply log this exactly once before even calling the plugins.

2021-01-12 00:17 UTC, swansontec commented on src/swap/changelly.js
> +      log.warn(`${pluginId} SwapCurrencyError ${JSON.stringify(request)}`)
We should probably not log these errors - the core already has centralized logging logic for dealing with all the swaps as a group. If we honestly want all errors logged, we should simply adjust the core, not all the plugins.

2021-01-13 02:16 UTC, paullinator commented
Per @swansontec's suggestions, it looks like logging is best done in the core and this pr can be closed.

2021-01-14 22:16 UTC, closed without merging