Feat/tomb-swap
EdgeApp/edge-exchange-plugins pull request #189
Opened 2022-04-15 23:04 UTC by Jon-edge

2022-04-19 21:42 UTC, samholmes requested changes
Some preliminary review comments. Primarily, we should break up the first commit we can review the changes there vs file/identifier renames.

2022-04-20 22:01 UTC, Jon-edge commented on src/abi/UNISWAP_V2_WERC20_ABI.js
> +// ABI for wrapped tokens
8ae3eab183de1783769ed1949ac755311b9dc21d

2022-04-20 22:14 UTC, Jon-edge commented on src/swap/defi/uni-v2-based/uniV2Contracts.js
> +export const wFtmTokenContract: Contract = (provider: JsonRpcProvider) =>
f10704f96943a497b26b18c28ba1f50755b7013e

I personally don't mind long names, and find value in having type identifying information in var names. Prevents ambiguity at a glance anywhere.

2022-04-21 19:34 UTC, samholmes requested changes

2022-04-21 19:34 UTC, samholmes commented on src/swap/spookySwap/spookySwap.js
> -
Can we swap between different EVM accounts?

2022-04-21 19:34 UTC, samholmes commented on src/swap/spookySwap/spookySwap.js
> -  const { log } = opts
Hmm, logs are useful for support help

2022-04-21 19:34 UTC, samholmes commented on src/swap/defi/uni-v2-based/uniV2Contracts.js
> +// Wrapped Tokens
Couldn't we just have a factory function to make this contract type given an address? Then we could parameterize the plugin with either the address or the contract returned from the factory (similar to how we do it in stake-plugins).

2022-04-21 19:34 UTC, samholmes commented on src/swap/defi/uni-v2-based/plugins/tombSwap.js
> +export function makeTombSwapPlugin(
If the implementation is nearly the same as `makeSpookySwapPlugin` then why not `makeUniswapPlugin` with parameters in the plugin info which determine the contract address to use, etc?

2022-04-21 19:34 UTC, samholmes commented on src/swap/defi/uni-v2-based/uniV2Contracts.js
> +export const wFtmTokenContract: Contract = (provider: JsonRpcProvider) =>
I agree

2022-04-21 19:34 UTC, samholmes commented on src/swap/defi/uni-v2-based/uniV2Utils.js
> +  provider: JsonRpcProvider,
These functions feel like methods to the swap plugin rather than utils; don't you think?

2022-04-21 21:07 UTC, samholmes commented on src/swap/defi/uni-v2-based/plugins/tombSwap.js
> +export function makeTombSwapPlugin(
I'll secede this request for a later refactor.

2022-04-21 21:07 UTC, samholmes commented on src/swap/defi/uni-v2-based/uniV2Utils.js
> +  provider: JsonRpcProvider,
I'll secede this request for a later refactor.

2022-04-21 23:50 UTC, thehobbit85 approved these changes

2022-04-22 00:00 UTC, merged