Convert to typescript
EdgeApp/edge-exchange-plugins pull request #213
Opened 2022-09-12 17:27 UTC by paullinator

2022-09-17 02:36 UTC, samholmes reviewed
So far all of the changes look good. I'll need to dig deeper on this PR on Monday. I'm well into the big commit.

2022-09-20 00:16 UTC, samholmes requested changes
I see that the odd  `=== true` conditions were undid on the last commit, but why were they in place to begin?

Minor changes aside from a definite change regarding an unintended `!=`.

2022-09-20 00:16 UTC, samholmes commented on src/swap/godex.ts
> +        if (lt(toNativeAmount, nativeMin) === true) {
More `=== true`

2022-09-20 00:16 UTC, samholmes commented on src/swap/letsexchange.ts
> +        reply = asInfoReply(
Maybe annotate `reply: ReturnType<typeof asInfoReply>` at declaration?

2022-09-20 00:16 UTC, samholmes commented on src/swap/sideshift.ts
> +  const api = createSideshiftApi(SIDESHIFT_BASE_URL, io.fetch)
Another `fetchCors` logic change

2022-09-20 00:16 UTC, samholmes commented on test/demo.ts
> +showRate(edgeCorePlugins.coinbase, 'iso:USD', 'BTC').catch(e => console.log(e))
Perhaps use `console.error`?

2022-09-20 00:35 UTC, paullinator commented on src/rate/coingecko.ts
> +const coinGeckoMap: { [ccode: string]: string } = {
`ccode` is short for currencyCode

2022-09-20 00:48 UTC, paullinator commented on src/swap/sideshift.ts
> +    io.fetchCors != null || io.fetch
These should actually use fetchCors, not io.fetch. I'll fix it.

2022-09-20 00:48 UTC, paullinator commented on src/rate/coincap.ts
> +  const fetch = io.fetchCors != null || io.fetch
These should actually use fetchCors, not io.fetch. I'll fix it.

2022-09-20 00:53 UTC, paullinator commented on src/swap/foxExchange.ts
> -          destinationAddress,
only in commented out code in the action queue. This was moved to EdgeSwapResult vs EdgeSwapQuote

2022-09-20 00:58 UTC, paullinator commented on src/swap/changenow.ts
> +        if (lt(largeDenomAmount, minAmount.toString()) === true) {
Automation required it in one of the commits, then after some changes it auto removed the `=== true`. I believe it had to do with VSCode needing a reboot. I've found VSCode won't have up to date squiggly errors after a change to packages and rules until a reboot

2022-09-20 00:58 UTC, paullinator commented on src/swap/changenow.ts
> +          gt(largeDenomAmount, maxAmount.toString()) === true
same as above

2022-09-20 00:59 UTC, paullinator commented on src/swap/defi/thorchain.ts
> +  thorchain: 'THOR'
That's the correct name of the chain. We dont yet support the chain so it was not a bug 'yet'

2022-09-20 00:59 UTC, paullinator commented on src/swap/defi/thorchain.ts
> +          if (exchangeInfoResponse.ok === true) {
same as comment above

2022-09-20 00:59 UTC, paullinator commented on src/swap/defi/thorchain.ts
> +      if (iaResponse.ok === false) {
yep

2022-09-20 01:00 UTC, paullinator commented on src/swap/defi/uni-v2-based/uniV2Utils.ts
> +  if (amountToSwap == null || expectedAmountOut != null)
Good catch

2022-09-20 01:02 UTC, paullinator commented on src/swap/defi/uni-v2-based/uniV2Utils.ts
> +        makeWrappedFtmContract(provider).populateTransaction.deposit({
As Jon. I have NO idea how. I brought this up w/him. But I verified it works now

2022-09-20 01:03 UTC, paullinator commented on src/swap/defi/uni-v2-based/uniV2Utils.ts
> +  return out
They were already serial with the awaits that were in the array.

2022-09-20 01:20 UTC, paullinator commented on src/rate/coincap.ts
> +  const { fetch } = io
These should actually use fetchCors, not io.fetch. I'll fix it.

2022-09-20 16:45 UTC, samholmes approved these changes

2022-09-20 17:20 UTC, paullinator commented
/rebase

2022-09-20 17:21 UTC, merged