Fix thorchain quotes
EdgeApp/edge-exchange-plugins pull request #229
Opened 2022-10-31 22:41 UTC by the-eridanus

2022-11-01 00:05 UTC, paullinator requested changes

2022-11-01 00:05 UTC, paullinator commented on src/swap/defi/thorchain.ts
> +      let feeInDestCurrency = outboundFee
This appears to be missing the logic to convert the fee into the outbound asset for when the outbound asset is a token

2022-11-02 16:40 UTC, the-eridanus commented
latest commit looks good 👍

2022-11-08 06:04 UTC, paullinator commented
/rebase

2022-11-08 06:28 UTC, paullinator approved these changes

2022-11-08 06:28 UTC, merged