Add Rango Exchange plugin (take 2)
EdgeApp/edge-exchange-plugins pull request #330
Opened 2024-06-19 16:31 UTC by paullinator

### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [ ] Yes
- [ ] No

### Dependencies

 none

### Description

 none

2024-06-23 23:14 UTC, paullinator commented
My new commits address comments from original PR https://github.com/EdgeApp/edge-exchange-plugins/pull/322

2024-06-24 19:11 UTC, peachbits requested changes

2024-06-24 20:43 UTC, paullinator commented on src/swap/defi/rango.ts
> +      ...(referrerAddress != null &&
No we shouldn't enforce they exist as the plugin should be usable without referral fees.

2024-06-24 23:20 UTC, peachbits approved these changes

2024-06-24 23:25 UTC, merged